### ISSUE TITLE
Wierd results with search field

### ISSUE THREAD

**Issue by abrasion66** [FrodeSolheim/fs-uae-launcher#105]
When i type "Ghost" for example i found "Yo! Joe!" that's not match my search, same for "young" i found "Operation Spruance" and few others.
Is there any fuzzy search or something wrong ? or maybe it's just me again missing something

**Comment by FrodeSolheim** [comment]
It's because the game is also known as "Yo! Joe!: Beat the Ghosts" - so yes, the search is not limited to the displayed title. Operation Spruance is also known as "USS John Young 2: A Realistic Warship Simulation"

These are included in the results, since they could be relevant.

If you look at the edit page for, for example, https://openretro.org/amiga/operation-spruance/edit, you can see game_name_alt. Some game entries also have additional words in the search_terms field to aid with searching.

**Comment by abrasion66** [comment]
Okay, thanks you for the light in my darkness of knowledge
